# Generated by Django 4.0 on 2022-02-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=30)),
                ('Patient_age', models.IntegerField()),
                ('patient_problem', models.CharField(max_length=150)),
                ('time', models.DateField(verbose_name='date registered')),
            ],
        ),
    ]
