# Generated by Django 4.0 on 2022-02-24 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient_details', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Patient_age',
            new_name='patient_age',
        ),
    ]
